version: "3"

networks:
  bunnynet:
    driver: bridge

services:
  openobserve:
    image: openobserve/openobserve:v0.12.1
    restart: unless-stopped
    volumes:
      - ./data/openob:/data  # Maps the local 'data' directory to '/data' in the container
    environment:
      ZO_ROOT_USER_EMAIL: ${SEARCH_EMAIL}
      ZO_ROOT_USER_PASSWORD: ${SEARCH_PWD}
    ports: ["5080:5080"]
    networks: [bunnynet]

  prometheus:
    image: prom/prometheus:v2.54.1
    user: root
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yaml --web.config.file=/etc/prometheus/web.yaml --web.route-prefix=/ --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=90d --web.enable-lifecycle --web.enable-admin-api
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./data/web.yaml:/etc/prometheus/web.yaml
      - ./data/prom:/prometheus
    networks: [bunnynet]

  vector:
    image: timberio/vector:0.X-alpine
    restart: unless-stopped
    ports: ["6514:6514/udp", "9598:9598"]
    volumes:
      - ./data/vector.yaml:/etc/vector/vector.yaml
      - ./data/vector:/logs
    environment:
      SEARCH_EMAIL: ${SEARCH_EMAIL}
      SEARCH_PWD: ${SEARCH_PWD}
      PROM_USER: ${PROM_USER}
      PROM_PWD: ${PROM_PWD}
      BUNNY_TOKEN: ${BUNNY_TOKEN}
    networks: [bunnynet]
    depends_on: [openobserve, prometheus]
