# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Remote write configuration
remote_write:
  - url: 'http://openobserve:5080/api/default/prometheus/api/v1/write'
    basic_auth:
      username: 'friends@niiknow.org'
      password: 'Complexpass#123'

# Usernames and hashed passwords that have full access to the web
# server via basic authentication. If empty, no basic authentication is
# required. Passwords are hashed with bcrypt.
basic_auth_users:
  friends: $2b$12$/Wq7mRwo8WGX0T3HIuHlD.9oeWlCxuOMMUiSmtk3aWohlAUY1yQOK

